# Generated by Django 4.1.3 on 2022-11-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.BigIntegerField()),
                ("timestamp", models.DateTimeField(max_length=200)),
                ("location_long", models.CharField(max_length=200)),
                ("location_lat", models.CharField(max_length=200)),
                ("individual_taxon_canonical_name", models.CharField(max_length=200)),
                ("tag_local_identifier", models.CharField(max_length=200)),
                ("individual_local_identifier", models.CharField(max_length=200)),
            ],
        ),
    ]
