# Generated by Django 4.1.3 on 2022-11-25 03:23
import csv
from django.db import migrations
from django.conf import settings
from pathlib import Path


model_name = 'Animal'
base_dir = settings.BASE_DIR

def insert_data(apps, schema_editor):
  csv_path = Path(base_dir, 'main/data/migration_original.csv')
  model = apps.get_model('main', model_name)
  all_data = []
  with open(csv_path, 'r') as file:
    reader = csv.reader(file)
    for i, row in enumerate(reader):
      if i > 1:
        data = {
          'event_id': row[0],
          'timestamp': row[1],
          'location_long': row[2],
          'location_lat': row[3],
          'individual_taxon_canonical_name': row[4],
          'tag_local_identifier': row[5],
          'individual_local_identifier': row[6]
          }
        all_data.append(data)
  all_model_instances = [model(**x) for x in all_data]
  model.objects.bulk_create(all_model_instances)
      


class Migration(migrations.Migration):

    dependencies = [
      ("main", "0001_initial"),
    ]

    operations = [
      migrations.RunPython(insert_data)
    ]
